import { StyleSheet, Dimensions } from 'react-native';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0f172a',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 20,
    },
    viewButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(31, 41, 55, 0.6)',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 25,
    },
    viewButtonTextOrange: {
        color: '#fb923c',
        fontSize: 16,
        fontWeight: '600',
    },
    viewButtonTextGray: {
        color: '#9ca3af',
        fontSize: 16,
        fontWeight: '600',
    },
    addButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scrollContent: {
        flex: 1,
        paddingHorizontal: 20,
    },
    scrollContentContainer: {
        paddingBottom: 20,
    },
    locationContainer: {
        marginBottom: 16,
        position: 'relative',
    },
    locationCard: {
        borderRadius: 24,
        overflow: 'hidden',
    },
    gradient: {
        padding: 24,
    },
    locationHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    locationInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    dot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.6)',
    },
    cityName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'white',
        marginBottom: 4,
    },
    locationSubtext: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    timeDisplay: {
        alignItems: 'flex-end',
    },
    timeText: {
        fontSize: 28,
        fontWeight: 'bold',
        color: 'white',
    },
    dateText: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    sliderContainer: {
        height: 96,
        marginBottom: 24,
        position: 'relative',
    },
    ticksContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        height: '100%',
    },
    tickWrapper: {
        alignItems: 'center',
    },
    tick: {
        width: 1,
        height: 8,
        backgroundColor: 'rgba(255, 255, 255, 0.4)',
        marginBottom: 4,
    },
    tickHour: {
        height: 16,
    },
    tickLabel: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.7)',
        fontWeight: '500',
    },
    centerIndicator: {
        position: 'absolute',
        left: '50%',
        top: 0,
        bottom: 0,
        width: 4,
        backgroundColor: '#ef4444',
        borderRadius: 2,
        transform: [{ translateX: -2 }],
    },
    centerDot: {
        position: 'absolute',
        top: '50%',
        left: -8,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#ef4444',
        borderWidth: 2,
        borderColor: 'white',
        transform: [{ translateY: -10 }],
    },
    weekContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    dayButton: {
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 8,
        borderRadius: 8,
    },
    dayButtonSelected: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    dayLabel: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.7)',
        marginBottom: 4,
    },
    dayNumber: {
        fontSize: 18,
        fontWeight: '600',
        color: 'rgba(255, 255, 255, 0.8)',
    },
    dayNumberSelected: {
        color: 'white',
    },
    calendarButton: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 8,
    },
    swipeActions: {
        position: 'absolute',
        right: 16,
        top: 0,
        bottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    actionButton: {
        width: 80,
        height: 80,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    deleteButton: {
        backgroundColor: '#ef4444',
    },
    pinButton: {
        backgroundColor: '#3b82f6',
    },
    actionButtonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '500',
        marginTop: 4,
    },
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 80,
    },
    emptyText: {
        fontSize: 18,
        color: '#6b7280',
        marginTop: 16,
    },
    emptySubtext: {
        fontSize: 14,
        color: '#4b5563',
        marginTop: 8,
    },
    bottomButtons: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        paddingVertical: 24,
        gap: 12,
        backgroundColor: 'rgba(15, 23, 42, 0.95)',
    },
    bottomButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: 'rgba(31, 41, 55, 0.6)',
        paddingVertical: 12,
        borderRadius: 25,
    },
    bottomButtonDisabled: {
        opacity: 0.5,
    },
    bottomButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '500',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    viewMenu: {
        backgroundColor: 'rgba(31, 41, 55, 0.95)',
        borderRadius: 16,
        minWidth: 200,
        padding: 8,
        marginHorizontal: 20,
    },
    viewMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    viewMenuButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
    },
    viewMenuText: {
        color: '#d1d5db',
        fontSize: 16,
    },
    viewMenuTextActive: {
        color: '#fb923c',
        fontWeight: '600',
    },
    deleteViewButton: {
        padding: 12,
    },
    viewMenuDivider: {
        height: 1,
        backgroundColor: '#374151',
        marginVertical: 8,
    },
    addViewContainer: {
        padding: 12,
    },
    addViewInput: {
        backgroundColor: '#374151',
        color: 'white',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        fontSize: 14,
        marginBottom: 8,
    },
    addViewButtons: {
        flexDirection: 'row',
        gap: 8,
    },
    addViewButtonConfirm: {
        flex: 1,
        backgroundColor: '#3b82f6',
        paddingVertical: 6,
        borderRadius: 8,
        alignItems: 'center',
    },
    addViewButtonCancel: {
        flex: 1,
        backgroundColor: '#374151',
        paddingVertical: 6,
        borderRadius: 8,
        alignItems: 'center',
    },
    addViewButtonText: {
        color: 'white',
        fontSize: 14,
    },
    addViewMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
    },
    addViewMenuText: {
        color: '#3b82f6',
        fontSize: 16,
        fontWeight: '500',
    },
    locationPopup: {
        backgroundColor: 'rgba(31, 41, 55, 0.95)',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        maxHeight: SCREEN_HEIGHT * 0.7,
        width: '100%',
        position: 'absolute',
        bottom: 0,
    },
    locationPopupHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 24,
        borderBottomWidth: 1,
        borderBottomColor: '#374151',
    },
    locationPopupTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
    },
    searchInput: {
        backgroundColor: 'rgba(55, 65, 81, 0.5)',
        color: 'white',
        paddingHorizontal: 16,
        paddingVertical: 12,
        margin: 24,
        marginTop: 16,
        borderRadius: 12,
        fontSize: 16,
    },
    locationList: {
        maxHeight: 400,
    },
    locationItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 16,
        borderTopWidth: 1,
        borderTopColor: 'rgba(55, 65, 81, 0.5)',
    },
    locationItemText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
    },
    locationItemOffset: {
        color: '#9ca3af',
        fontSize: 14,
    },
    calendarPopup: {
        backgroundColor: 'rgba(31, 41, 55, 0.95)',
        borderRadius: 24,
        padding: 24,
        maxWidth: 400,
        width: '90%',
        height: 450,
    },
    calendarHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    calendarArrow: {
        padding: 8,
    },
    calendarTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
    },
    calendarDayLabelsRow: {
        flexDirection: 'row',
        marginBottom: 8,
    },
    calendarGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        rowGap: 8,
    },
    calendarDayLabel: {
        width: `${100 / 7}%`,
        textAlign: 'center',
        color: '#9ca3af',
        fontSize: 14,
        paddingVertical: 8,
    },
    calendarDay: {
        width: `${100 / 7}%`,
        aspectRatio: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 8,
    },
    calendarDaySelected: {
        backgroundColor: '#3b82f6',
        borderRadius: 8,
        padding: 0,
    },
    calendarDayText: {
        color: 'white',
        fontSize: 14,
    },
    calendarDayTextSelected: {
        fontWeight: 'bold',
    },
    calendarDayTextEmpty: {
        color: 'transparent',
    },
    monthGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        rowGap: 12,
    },
    monthButton: {
        width: `${100 / 3}%`,
        paddingVertical: 16,
        alignItems: 'center',
        borderRadius: 8,
    },
    monthButtonText: {
        color: 'rgba(255, 255, 255, 0.8)',
        fontSize: 16,
        fontWeight: '500',
    },
});

export default styles;