import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  viewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(31, 41, 55, 0.6)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 25,
  },
  settingsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(31, 41, 55, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewButtonTextOrange: {
    color: '#fb923c',
    fontSize: 16,
    fontWeight: '600',
  },
  viewButtonTextGray: {
    color: '#9ca3af',
    fontSize: 16,
    fontWeight: '600',
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    flex: 1,
    paddingHorizontal: 20,
  },
  scrollContentContainer: {
    paddingBottom: 20,
  },
  locationContainer: {
    marginBottom: 16,
    position: 'relative',
  },
  locationCard: {
    borderRadius: 24,
    overflow: 'hidden',
  },
  gradient: {
    padding: 24,
  },
  locationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  locationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
  },
  cityName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 4,
  },
  locationSubtext: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  timeDisplay: {
    alignItems: 'flex-end',
  },
  timeText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: 'white',
  },
  dateText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  sliderContainer: {
    height: 96,
    marginTop: 12,
    marginBottom: 0,
    position: 'relative',
  },
  ticksContainer: {
    position: 'relative',
    height: '100%',
    width: '100%',
  },
  tickWrapper: {
    position: 'absolute',
    alignItems: 'flex-start',
  },
  tick: {
    width: 1,
    height: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    marginBottom: 4,
  },
  tickHour: {
    height: 16,
  },
  tickLabel: {
    position: 'absolute',
    top: 20,
    left: -50,
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '500',
    width: 100,
    textAlign: 'center',
  },
  centerIndicator: {
    position: 'absolute',
    left: '50%',
    top: '20%',
    width: 3,
    height: 50,
    backgroundColor: '#ef4444',
    borderRadius: 2,
    transform: [{ translateX: -1.5 }, { translateY: -20 }],
  },
  centerDot: {
    position: 'absolute',
    top: '50%',
    left: -8,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#ef4444',
    borderWidth: 2,
    borderColor: 'white',
    transform: [{ translateY: -10 }],
  },
  weekContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dayButton: {
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  dayButtonSelected: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  dayLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    marginBottom: 4,
  },
  dayNumber: {
    fontSize: 18,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.8)',
  },
  dayNumberSelected: {
    color: 'white',
  },
  calendarButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  swipeActions: {
    position: 'absolute',
    right: 16,
    top: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionButton: {
    width: 80,
    height: 80,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  deleteButton: {
    backgroundColor: '#ef4444',
  },
  pinButton: {
    backgroundColor: '#3b82f6',
  },
  actionButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
    marginTop: 4,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 80,
  },
  emptyText: {
    fontSize: 18,
    color: '#6b7280',
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#4b5563',
    marginTop: 8,
  },
  bottomButtons: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 24,
    gap: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
  },
  bottomButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(31, 41, 55, 0.6)',
    paddingVertical: 12,
    borderRadius: 25,
  },
  bottomButtonDisabled: {
    opacity: 0.5,
  },
  bottomButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewMenu: {
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderRadius: 16,
    minWidth: 200,
    padding: 8,
    marginHorizontal: 20,
  },
  viewMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewMenuButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  viewMenuText: {
    color: '#d1d5db',
    fontSize: 16,
  },
  viewMenuTextActive: {
    color: '#fb923c',
    fontWeight: '600',
  },
  deleteViewButton: {
    padding: 12,
  },
  viewMenuDivider: {
    height: 1,
    backgroundColor: '#374151',
    marginVertical: 8,
  },
  addViewContainer: {
    padding: 12,
  },
  addViewInput: {
    backgroundColor: '#374151',
    color: 'white',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    fontSize: 14,
    marginBottom: 8,
  },
  addViewButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  addViewButtonConfirm: {
    flex: 1,
    backgroundColor: '#3b82f6',
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
  },
  addViewButtonCancel: {
    flex: 1,
    backgroundColor: '#374151',
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
  },
  addViewButtonText: {
    color: 'white',
    fontSize: 14,
  },
  addViewMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  addViewMenuText: {
    color: '#3b82f6',
    fontSize: 16,
    fontWeight: '500',
  },
  locationPopup: {
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: SCREEN_HEIGHT * 0.7,
    width: '100%',
    position: 'absolute',
    bottom: 0,
  },
  locationPopupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  locationPopupTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  searchInput: {
    backgroundColor: 'rgba(55, 65, 81, 0.5)',
    color: 'white',
    paddingHorizontal: 16,
    paddingVertical: 12,
    margin: 24,
    marginTop: 16,
    borderRadius: 12,
    fontSize: 16,
  },
  pickerTagsContainer: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 4,
  },
  pickerTag: {
    backgroundColor: '#374151',
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginRight: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  pickerTagText: {
    color: 'white',
    fontWeight: '600',
  },
  locationList: {
    maxHeight: 300,
    marginBottom: 8,
  },
  locationItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(55, 65, 81, 0.5)',
  },
  locationItemSelected: {
    backgroundColor: 'rgba(59,130,246,0.12)',
  },
  locationItemText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  locationItemOffset: {
    color: '#9ca3af',
    fontSize: 14,
  },
  citySelectIndicator: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#9ca3af',
  },
  citySelectIndicatorActive: {
    backgroundColor: '#3b82f6',
    borderColor: '#3b82f6',
  },
  pickerButtonsRow: {
    flexDirection: 'row',
    gap: 12,
    padding: 24,
  },
  pickerButton: {
    flex: 1,
    backgroundColor: '#3b82f6',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  pickerButtonDisabled: {
    opacity: 0.5,
  },
  pickerButtonCancel: {
    flex: 1,
    backgroundColor: '#374151',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  pickerButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
  calendarPopup: {
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderRadius: 24,
    padding: 24,
    maxWidth: 400,
    width: '90%',
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  calendarArrow: {
    padding: 8,
  },
  calendarTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  calendarDayLabelsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  calendarDayLabel: {
    width: `${100 / 7}%`,
    textAlign: 'center',
    color: '#9ca3af',
    fontSize: 14,
    paddingVertical: 8,
  },
  monthGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  monthButton: {
    width: `${(100 - 8) / 3}%`,
    paddingVertical: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(55, 65, 81, 0.5)',
    alignItems: 'center',
  },
  monthButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
  },
  calendarDay: {
    width: `${100 / 7}%`,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  calendarDaySelected: {
    backgroundColor: '#3b82f6',
  },
  calendarDayText: {
    color: 'white',
    fontSize: 14,
  },
  calendarDayTextSelected: {
    fontWeight: 'bold',
  },
  calendarDayTextEmpty: {
    color: 'transparent',
  },
  settingsMenu: {
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderRadius: 16,
    minWidth: 200,
    padding: 8,
    marginHorizontal: 20,
  },
  settingsMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  settingsMenuText: {
    color: '#d1d5db',
    fontSize: 16,
  },
  settingsMenuTextDanger: {
    color: '#ef4444',
  },
  settingsMenuDivider: {
    height: 1,
    backgroundColor: '#374151',
    marginVertical: 8,
  },
  renameViewModal: {
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderRadius: 16,
    padding: 24,
    minWidth: 300,
    marginHorizontal: 20,
  },
  renameViewTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 16,
  },
  renameViewInput: {
    backgroundColor: '#374151',
    color: 'white',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 8,
    fontSize: 16,
    marginBottom: 16,
  },
  renameViewButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  renameViewButtonCancel: {
    flex: 1,
    backgroundColor: '#374151',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  renameViewButtonConfirm: {
    flex: 1,
    backgroundColor: '#3b82f6',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  renameViewButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
  },
  calendarAddPopup: {
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: '100%',
    position: 'absolute',
    bottom: 0,
    paddingBottom: 40,
  },
  calendarAddHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  calendarAddTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  calendarAddInfo: {
    padding: 24,
    paddingBottom: 16,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  calendarAddTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  calendarAddTimeText: {
    fontSize: 18,
    fontWeight: '600',
    color: 'white',
  },
  calendarAddSubtext: {
    fontSize: 14,
    color: '#9ca3af',
    marginLeft: 28,
  },
  calendarAddInput: {
    backgroundColor: 'rgba(55, 65, 81, 0.5)',
    color: 'white',
    paddingHorizontal: 16,
    paddingVertical: 12,
    margin: 24,
    marginBottom: 16,
    borderRadius: 12,
    fontSize: 16,
  },
  calendarAddNotesInput: {
    minHeight: 80,
    paddingTop: 12,
  },
  calendarAddDurationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  calendarAddDurationContainer: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  calendarAddLabel: {
    fontSize: 16,
    color: '#d1d5db',
    marginBottom: 12,
    fontWeight: '500',
  },
  calendarAddDurationInput: {
    backgroundColor: 'rgba(55, 65, 81, 0.5)',
    color: 'white',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    fontSize: 16,
    minWidth: 80,
    textAlign: 'center',
  },
  durationOptionsContainer: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  durationOption: {
    backgroundColor: 'rgba(55, 65, 81, 0.5)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  durationOptionSelected: {
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    borderColor: '#3b82f6',
  },
  durationOptionText: {
    color: '#d1d5db',
    fontSize: 14,
    fontWeight: '500',
  },
  durationOptionTextSelected: {
    color: '#3b82f6',
    fontWeight: '600',
  },
  calendarAddButtons: {
    paddingHorizontal: 24,
    gap: 12,
  },
  calendarAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#3b82f6',
    paddingVertical: 16,
    borderRadius: 12,
  },
  calendarAddButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
});

export default styles;
export { SCREEN_WIDTH, SCREEN_HEIGHT };
